export {
  addWakePhraseCommandListener,
  addWakePhraseDetectedListener,
  addWakePhraseDiagnosticListener,
  addWakePhraseStateListener,
  getWakePhraseState,
  initialWakePhraseState,
  prepareWakePhrasePlaybackRoute,
  requestWakePhrasePermissions,
  startWakePhraseListening,
  stopWakePhraseListening,
  type WakePhraseMode,
  type WakePhraseDiagnosticEvent,
  type WakePhrasePlaybackRoute,
  type WakePhraseState,
} from '../../modules/clio-meta-wearables';
