export {
  addNativeSpeechStateListener,
  addWakePhraseCommandListener,
  addWakePhraseDetectedListener,
  addWakePhraseDiagnosticListener,
  addWakePhraseStateListener,
  getWakePhraseState,
  initialWakePhraseState,
  prepareWakePhrasePlaybackRoute,
  requestWakePhrasePermissions,
  startNativeAnswerSpeech,
  startWakePhraseListening,
  stopNativeSpeech,
  stopWakePhraseListening,
  type NativeSpeechKind,
  type NativeSpeechStage,
  type NativeSpeechStateEvent,
  type WakePhraseMode,
  type WakePhraseDiagnosticEvent,
  type WakePhrasePlaybackRoute,
  type WakePhraseState,
} from '../../modules/clio-meta-wearables';
